export const messagesData = [
  "Tu es mon plus beau cadeau ❤️",
  "Chaque jour avec toi est une bénédiction",
  "Mon cœur t’appartient pour toujours",
  "Merci d’être dans ma vie",
  "Je t’aime plus que hier, moins que demain",
  "Ton sourire illumine mes journées",
  "Avec toi, tout devient plus beau",
  "Tu fais battre mon cœur plus fort",
  "Tu es mon rayon de soleil",
  "Mon amour pour toi grandit chaque jour",

  "Tu es la plus belle chose qui me soit arrivée",
  "À tes côtés, je me sens chez moi",
  "Ton amour est ma force",
  "Je pense à toi à chaque instant",
  "Tu rends ma vie magique",
  "Tu es mon rêve devenu réalité",
  "Mon cœur te choisit chaque jour",
  "Je suis chanceux(se) de t’avoir",
  "Tu es mon bonheur",
  "Je t’aime infiniment",

  "Ton regard me fait fondre",
  "Ta présence me rassure",
  "Tu es mon évidence",
  "Avec toi, je souris sans raison",
  "Tu es mon miracle quotidien",
  "Je t’aime de tout mon cœur",
  "Tu complètes ma vie",
  "Ton amour est mon trésor",
  "Je suis fou/folle de toi",
  "Tu es mon âme sœur",

  "Chaque moment avec toi est précieux",
  "Tu fais vibrer mon cœur",
  "Je veux vieillir avec toi",
  "Tu es mon plus doux bonheur",
  "Ton amour m’inspire",
  "Tu es mon plus beau chapitre",
  "Je te choisis aujourd’hui et toujours",
  "Tu es ma paix",
  "Mon cœur sourit grâce à toi",
  "Je t’aime sans condition",

  "Tu es mon étoile",
  "Ton amour éclaire mon chemin",
  "Tu es mon refuge",
  "Je ne veux que toi",
  "Tu es ma plus belle habitude",
  "Je t’aime plus que les mots",
  "Tu es mon univers",
  "Ton amour est ma maison",
  "Tu es ma moitié",
  "Je t’aimerai toujours",

  "Tu es mon bonheur quotidien",
  "Je suis tombé(e) amoureux(se) de ton âme",
  "Tu rends tout plus doux",
  "Tu es ma priorité",
  "Ton amour me rend meilleur(e)",
  "Je te garde dans mon cœur",
  "Tu es mon destin",
  "Je suis à toi",
  "Tu es mon trésor",
  "Je t’aime à l’infini",

  "Tu es mon sourire préféré",
  "Mon cœur bat pour toi",
  "Tu es mon éternité",
  "Je t’aime aujourd’hui, demain, toujours",
  "Tu es mon plus beau rêve",
  "Avec toi, je me sens vivant(e)",
  "Tu es mon bonheur absolu",
  "Je ne vois que toi",
  "Tu es mon tout",
  "Je t’aime plus que tout ❤️"
]
